language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

services:
  - mysql

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
before_install:
  - composer install --dev
  - mysql -e "create database IF NOT EXISTS codemaven_test;" -u root

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
